In [2]:
import random

a = random.random()
print(a)

0.31285141343217016


In [6]:
a = random.uniform(1, 10) # give start and stop
print(a)

3.1322840228194937


In [13]:
# for integer
a = random.randint(1, 10)
print(a)

4


In [14]:
# never pick the 10
a = random.randint(1, 10)
print(a)

7


In [21]:
a = random.normalvariate(0, 1) #useful if working in statistics mean of 0 and standard deviation 1 - normal dist
print(a)

0.5799934933512348


In [24]:
my_list = list("ABCDEFGH")
print(my_list)
a = random.choice(my_list)
print(a)


['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
C


In [27]:
# to pick more elements
a = random.sample(my_list, 3) # 3 is total number of elements
print(a)

['C', 'B', 'A']


In [31]:
# to pick more element multiple times
a = random.choices(my_list, k=3)
print(a)

['G', 'F', 'A']


In [32]:
random.shuffle(my_list)
print(my_list)

['H', 'F', 'D', 'C', 'E', 'G', 'A', 'B']


In [35]:
random.seed(1) # reproduce with data with random with seed
print(random.random())
print(random.randint(1, 10))

random.seed(2)
print(random.random())
print(random.randint(1, 10))

0.13436424411240122
2
0.9560342718892494
1


In [36]:
import secrets

a = secrets.randbelow(10)
print(a)


9


In [37]:
a = secrets.randbits(4)
print(a)

8


In [40]:
mylist = list("ABCDEFGH")
a = secrets.choice(mylist)
print(a)

A


In [46]:
# working with arrays
import numpy as np

a = np.random.rand(3)
print(a)

[0.54975525 0.33351908 0.55934173]


In [63]:
a = np.random.randint(0, 10, (3, 4))
print(a)

[[8 0 6 8]
 [9 7 0 9]
 [3 3 3 2]]


In [70]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)
np.random.shuffle(arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [1 2 3]
 [4 5 6]]


In [72]:
np.random.seed(1)
print(np.random.rand(3, 3))

np.random.seed(2)
print(np.random.rand(3,3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
[[0.4359949  0.02592623 0.54966248]
 [0.43532239 0.4203678  0.33033482]
 [0.20464863 0.61927097 0.29965467]]
